# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchInTwitterExample' do
pod "SearchInTwitter"
  # use_frameworks!

  # Pods for SearchInTwitterExample

end
